name: "Demo.Aci.DbMigrations"
concurrency: "Demo.Aci.DbMigrations"
env:
  DOTNET_VERSION: 6.0.x
  APP_NAME: bankaccounts
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
        
  workflow_dispatch:
      
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test Database Migrations
        uses: ./.github/workflows/run-tests.yml
        
  build:
    name: Create artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
          
      - name: Publish Artifacts - Deployment Templates
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: ./.github/templates
          if-no-files-found: error    

  deploytodev:
    environment: DEV
    name: DEV
    runs-on: ubuntu-latest
    needs: build
    env:
      ENVNAME: "dev"
      IMAGE_NAME: "demo.db.bankaccounts"
      RG_NAME: rg-bankaccounts-dev
      RG_LOCATION: australiasoutheast
      
    steps:
      - name: Generate Build Number
        id: generatebuildnumber
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Build Image and Publish
        uses: Cheranga/GitHubActions/buildandpushtodockerhub@master
        with:
          dockerUserName: ${{secrets.DOCKER_USER}}
          dockerPassword: ${{secrets.DOCKER_PASSWORD}}
          dockerFilePath: BankingDataStore.Console/Dockerfile
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: ${{ env.BUILD_VERSION }}       

      - name: Create Resource Group - ${{ env.RG_NAME }}
        uses: Cheranga/GitHubActions/createresourcegroup@master
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          name: ${{ env.RG_NAME }}
          location: ${{ env.RG_LOCATION }}  

      - name: Download Artifact - Templates
        uses: actions/download-artifact@v3
        with:
          name: deploy
          path: deploy          

      - name: Login to Azure CLI       
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      

      - name: Provision Resources
        env:
          DATABASE_SERVER: ccdemosqlserverdev
          SQL_SERVER_LOCATION: australiaeast
        uses: azure/arm-deploy@v1
        with:
          failOnStdErr: false
          deploymentName: ${{ env.BUILD_VERSION }}-${{ env.APP_NAME }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: deploy/main.bicep
          parameters: >            
            buildNumber=${{ env.BUILD_VERSION }} 
            appName=${{ env.APP_NAME }} 
            environmentName=${{ env.APP_NAME }} 
            location=${{ env.RG_LOCATION }} 
            containerImage=${{ secrets.DOCKER_USER }}/demo.db.bankaccounts:${{ env.BUILD_VERSION }} 
            sqlServerLocation=${{ env.SQL_SERVER_LOCATION }} 
            databaseServerName=${{ env.DATABASE_SERVER }} 
            databaseName=${{ secrets.DATABASE_NAME }} 
            databaseUserName=${{ secrets.DATABASE_USERNAME }} 
            databasePassword=${{ secrets.DATABASE_PASSWORD }} 
      - name: Logout from Azure CLI     
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout                                 