name: "PR Build"

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]

jobs:
  SND:
    name: SND
    needs: installations
    uses: ./.github/workflows/run-tests.yml
    with:
      projectName: Demo.Selenium.Bank
      environment: snd
    secrets:
      userName: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
  
  DEV:
    name: DEV
    needs: installations
    uses: ./.github/workflows/run-tests.yml
    with:
      projectName: Demo.Selenium.Bank
      environment: dev
    secrets:
      userName: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}